services:
  - type: web
    name: scraper-backend
    runtime: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run dev
    envVars:
      - key: MONGODB_URI
        value: MONGODB_URI
      - key: PORT
        value: 8080
      - key: FRONTEND_URL
        value: FRONTEND_URL
